### ISSUE TITLE
Exceptions with java 11

### ISSUE THREAD

**Issue by Robson96** [spotify/folsom#156]
executes and returns the value successfully, but it throws several exceptions!!

Here is log.

/home/scala/.sdkman/candidates/java/11.0.8.j9-adpt/bin/java -javaagent:/snap/intellij-idea-community/246/lib/idea_rt.jar=38149:/snap/intellij-idea-community/246/bin -Dfile.encoding=UTF-8 -classpath /home/scala/Documentos/memcached-falson/target/classes:/home/scala/.m2/repository/com/spotify/folsom/1.7.3/folsom-1.7.3.jar:/home/scala/.m2/repository/com/spotify/completable-futures/0.3.2/completable-futures-0.3.2.jar:/home/scala/.m2/repository/com/google/guava/guava/28.0-android/guava-28.0-android.jar:/home/scala/.m2/repository/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar:/home/scala/.m2/repository/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar:/home/scala/.m2/repository/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar:/home/scala/.m2/repository/org/checkerframework/checker-compat-qual/2.5.5/checker-compat-qual-2.5.5.jar:/home/scala/.m2/repository/com/google/errorprone/error_prone_annotations/2.3.2/error_prone_annotations-2.3.2.jar:/home/scala/.m2/repository/com/google/j2objc/j2objc-annotations/1.3/j2objc-annotations-1.3.jar:/home/scala/.m2/repository/org/codehaus/mojo/animal-sniffer-annotations/1.17/animal-sniffer-annotations-1.17.jar:/home/scala/.m2/repository/org/slf4j/slf4j-api/1.7.5/slf4j-api-1.7.5.jar:/home/scala/.m2/repository/io/netty/netty-transport/4.1.34.Final/netty-transport-4.1.34.Final.jar:/home/scala/.m2/repository/io/netty/netty-common/4.1.34.Final/netty-common-4.1.34.Final.jar:/home/scala/.m2/repository/io/netty/netty-buffer/4.1.34.Final/netty-buffer-4.1.34.Final.jar:/home/scala/.m2/repository/io/netty/netty-resolver/4.1.34.Final/netty-resolver-4.1.34.Final.jar:/home/scala/.m2/repository/io/netty/netty-codec/4.1.34.Final/netty-codec-4.1.34.Final.jar:/home/scala/.m2/repository/io/netty/netty-transport-native-epoll/4.1.34.Final/netty-transport-native-epoll-4.1.34.Final.jar:/home/scala/.m2/repository/io/netty/netty-transport-native-unix-common/4.1.34.Final/netty-transport-native-unix-common-4.1.34.Final.jar:/home/scala/.m2/repository/com/spotify/dns/3.1.4/dns-3.1.4.jar:/home/scala/.m2/repository/dnsjava/dnsjava/2.1.7/dnsjava-2.1.7.jar:/home/scala/.m2/repository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar:/home/scala/.m2/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar:/home/scala/.m2/repository/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3.jar org.example.App
12:51:55.362 [main] DEBUG io.netty.util.internal.logging.InternalLoggerFactory - Using SLF4J as the default logging framework
12:51:56.080 [main] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.initialSize: 1024
12:51:56.080 [main] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.maxSize: 4096
12:51:56.462 [main] DEBUG io.netty.util.internal.PlatformDependent0 - -Dio.netty.noUnsafe: false
12:51:56.464 [main] DEBUG io.netty.util.internal.PlatformDependent0 - Java version: 11
12:51:56.534 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
12:51:56.594 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
12:51:56.598 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
12:51:56.617 [main] DEBUG io.netty.util.internal.PlatformDependent0 - direct buffer constructor: unavailable
java.lang.UnsupportedOperationException: Reflective setAccessible(true) disabled
	at io.netty.util.internal.ReflectionUtil.trySetAccessible(ReflectionUtil.java:31)
	at io.netty.util.internal.PlatformDependent0$4.run(PlatformDependent0.java:224)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:678)
	at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:218)
	at io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:213)
	at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:81)
	at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:195)
	at io.netty.channel.epoll.Native.<clinit>(Native.java:61)
	at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:38)
	at com.spotify.folsom.client.DefaultRawMemcacheClient.lambda$static$0(DefaultRawMemcacheClient.java:96)
	at com.spotify.folsom.client.DefaultRawMemcacheClient$$Lambda$29/0000000000000000.get(Unknown Source)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:167)
	at com.spotify.folsom.client.DefaultRawMemcacheClient.connect(DefaultRawMemcacheClient.java:138)
	at com.spotify.folsom.reconnect.ReconnectingClient.lambda$new$0(ReconnectingClient.java:80)
	at com.spotify.folsom.reconnect.ReconnectingClient$$Lambda$27/0000000000000000.connect(Unknown Source)
	at com.spotify.folsom.authenticate.AuthenticatingClient.authenticate(AuthenticatingClient.java:28)
	at com.spotify.folsom.reconnect.ReconnectingClient.lambda$new$1(ReconnectingClient.java:105)
	at com.spotify.folsom.reconnect.ReconnectingClient$$Lambda$28/0000000000000000.connect(Unknown Source)
	at com.spotify.folsom.reconnect.ReconnectingClient.retry(ReconnectingClient.java:157)
	at com.spotify.folsom.reconnect.ReconnectingClient.<init>(ReconnectingClient.java:120)
	at com.spotify.folsom.reconnect.ReconnectingClient.<init>(ReconnectingClient.java:102)
	at com.spotify.folsom.reconnect.ReconnectingClient.<init>(ReconnectingClient.java:76)
	at com.spotify.folsom.MemcacheClientBuilder.createReconnectingClient(MemcacheClientBuilder.java:651)
	at com.spotify.folsom.MemcacheClientBuilder.createClient(MemcacheClientBuilder.java:632)
	at com.spotify.folsom.MemcacheClientBuilder.createClients(MemcacheClientBuilder.java:608)
	at com.spotify.folsom.MemcacheClientBuilder.connectRaw(MemcacheClientBuilder.java:581)
	at com.spotify.folsom.MemcacheClientBuilder.connectAscii(MemcacheClientBuilder.java:558)
	at org.example.App.main(App.java:21)
12:51:56.624 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: available, true
12:51:56.626 [main] DEBUG io.netty.util.internal.PlatformDependent0 - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable
java.lang.IllegalAccessException: class io.netty.util.internal.PlatformDependent0$6 cannot access class jdk.internal.misc.Unsafe (in module java.base) because module java.base does not export jdk.internal.misc to unnamed module @35f3676b
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:361)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:591)
	at java.base/java.lang.reflect.Method.invoke(Method.java:558)
	at io.netty.util.internal.PlatformDependent0$6.run(PlatformDependent0.java:334)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:678)
	at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:325)
	at io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:213)
	at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:81)
	at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:195)
	at io.netty.channel.epoll.Native.<clinit>(Native.java:61)
	at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:38)
	at com.spotify.folsom.client.DefaultRawMemcacheClient.lambda$static$0(DefaultRawMemcacheClient.java:96)
	at com.spotify.folsom.client.DefaultRawMemcacheClient$$Lambda$29/0000000000000000.get(Unknown Source)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:167)
	at com.spotify.folsom.client.DefaultRawMemcacheClient.connect(DefaultRawMemcacheClient.java:138)
	at com.spotify.folsom.reconnect.ReconnectingClient.lambda$new$0(ReconnectingClient.java:80)
	at com.spotify.folsom.reconnect.ReconnectingClient$$Lambda$27/0000000000000000.connect(Unknown Source)
	at com.spotify.folsom.authenticate.AuthenticatingClient.authenticate(AuthenticatingClient.java:28)
	at com.spotify.folsom.reconnect.ReconnectingClient.lambda$new$1(ReconnectingClient.java:105)
	at com.spotify.folsom.reconnect.ReconnectingClient$$Lambda$28/0000000000000000.connect(Unknown Source)
	at com.spotify.folsom.reconnect.ReconnectingClient.retry(ReconnectingClient.java:157)
	at com.spotify.folsom.reconnect.ReconnectingClient.<init>(ReconnectingClient.java:120)
	at com.spotify.folsom.reconnect.ReconnectingClient.<init>(ReconnectingClient.java:102)
	at com.spotify.folsom.reconnect.ReconnectingClient.<init>(ReconnectingClient.java:76)
	at com.spotify.folsom.MemcacheClientBuilder.createReconnectingClient(MemcacheClientBuilder.java:651)
	at com.spotify.folsom.MemcacheClientBuilder.createClient(MemcacheClientBuilder.java:632)
	at com.spotify.folsom.MemcacheClientBuilder.createClients(MemcacheClientBuilder.java:608)
	at com.spotify.folsom.MemcacheClientBuilder.connectRaw(MemcacheClientBuilder.java:581)
	at com.spotify.folsom.MemcacheClientBuilder.connectAscii(MemcacheClientBuilder.java:558)
	at org.example.App.main(App.java:21)
12:51:56.629 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, int): unavailable
12:51:56.630 [main] DEBUG io.netty.util.internal.PlatformDependent - sun.misc.Unsafe: available
12:51:56.826 [main] DEBUG io.netty.util.internal.PlatformDependent - maxDirectMemory: 1026686976 bytes (maybe)
12:51:56.826 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.tmpdir: /tmp (java.io.tmpdir)
12:51:56.826 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
12:51:56.830 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.maxDirectMemory: -1 bytes
12:51:56.831 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.uninitializedArrayAllocationThreshold: -1
12:51:56.834 [main] DEBUG io.netty.util.internal.CleanerJava9 - java.nio.ByteBuffer.cleaner(): available
12:51:56.845 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
12:51:56.900 [main] DEBUG io.netty.util.internal.NativeLibraryLoader - -Dio.netty.native.workdir: /tmp (io.netty.tmpdir)
12:51:56.901 [main] DEBUG io.netty.util.internal.NativeLibraryLoader - -Dio.netty.native.deleteLibAfterLoading: true
12:51:56.901 [main] DEBUG io.netty.util.internal.NativeLibraryLoader - -Dio.netty.native.tryPatchShadedId: true
12:51:56.927 [main] DEBUG io.netty.util.internal.NativeLibraryLoader - Unable to load the library 'netty_transport_native_epoll_x86_64', trying other loading mechanism.
java.lang.UnsatisfiedLinkError: netty_transport_native_epoll_x86_64 (Not found in java.library.path)
	at java.base/java.lang.ClassLoader.loadLibraryWithPath(ClassLoader.java:1742)
	at java.base/java.lang.ClassLoader.loadLibraryWithClassLoader(ClassLoader.java:1694)
	at java.base/java.lang.System.loadLibrary(System.java:598)
	at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:369)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:678)
	at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:361)
	at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:339)
	at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
	at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:198)
	at io.netty.channel.epoll.Native.<clinit>(Native.java:61)
	at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:38)
	at com.spotify.folsom.client.DefaultRawMemcacheClient.lambda$static$0(DefaultRawMemcacheClient.java:96)
	at com.spotify.folsom.client.DefaultRawMemcacheClient$$Lambda$29/0000000000000000.get(Unknown Source)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:167)
	at com.spotify.folsom.client.DefaultRawMemcacheClient.connect(DefaultRawMemcacheClient.java:138)
	at com.spotify.folsom.reconnect.ReconnectingClient.lambda$new$0(ReconnectingClient.java:80)
	at com.spotify.folsom.reconnect.ReconnectingClient$$Lambda$27/0000000000000000.connect(Unknown Source)
	at com.spotify.folsom.authenticate.AuthenticatingClient.authenticate(AuthenticatingClient.java:28)
	at com.spotify.folsom.reconnect.ReconnectingClient.lambda$new$1(ReconnectingClient.java:105)
	at com.spotify.folsom.reconnect.ReconnectingClient$$Lambda$28/0000000000000000.connect(Unknown Source)
	at com.spotify.folsom.reconnect.ReconnectingClient.retry(ReconnectingClient.java:157)
	at com.spotify.folsom.reconnect.ReconnectingClient.<init>(ReconnectingClient.java:120)
	at com.spotify.folsom.reconnect.ReconnectingClient.<init>(ReconnectingClient.java:102)
	at com.spotify.folsom.reconnect.ReconnectingClient.<init>(ReconnectingClient.java:76)
	at com.spotify.folsom.MemcacheClientBuilder.createReconnectingClient(MemcacheClientBuilder.java:651)
	at com.spotify.folsom.MemcacheClientBuilder.createClient(MemcacheClientBuilder.java:632)
	at com.spotify.folsom.MemcacheClientBuilder.createClients(MemcacheClientBuilder.java:608)
	at com.spotify.folsom.MemcacheClientBuilder.connectRaw(MemcacheClientBuilder.java:581)
	at com.spotify.folsom.MemcacheClientBuilder.connectAscii(MemcacheClientBuilder.java:558)
	at org.example.App.main(App.java:21)
12:51:56.931 [main] DEBUG io.netty.util.internal.NativeLibraryLoader - netty_transport_native_epoll_x86_64 cannot be loaded from java.libary.path, now trying export to -Dio.netty.native.workdir: /tmp
java.lang.UnsatisfiedLinkError: netty_transport_native_epoll_x86_64 (Not found in java.library.path)
	at java.base/java.lang.ClassLoader.loadLibraryWithPath(ClassLoader.java:1742)
	at java.base/java.lang.ClassLoader.loadLibraryWithClassLoader(ClassLoader.java:1694)
	at java.base/java.lang.System.loadLibrary(System.java:598)
	at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
	at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:349)
	at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
	at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:198)
	at io.netty.channel.epoll.Native.<clinit>(Native.java:61)
	at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:38)
	at com.spotify.folsom.client.DefaultRawMemcacheClient.lambda$static$0(DefaultRawMemcacheClient.java:96)
	at com.spotify.folsom.client.DefaultRawMemcacheClient$$Lambda$29/0000000000000000.get(Unknown Source)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:167)
	at com.spotify.folsom.client.DefaultRawMemcacheClient.connect(DefaultRawMemcacheClient.java:138)
	at com.spotify.folsom.reconnect.ReconnectingClient.lambda$new$0(ReconnectingClient.java:80)
	at com.spotify.folsom.reconnect.ReconnectingClient$$Lambda$27/0000000000000000.connect(Unknown Source)
	at com.spotify.folsom.authenticate.AuthenticatingClient.authenticate(AuthenticatingClient.java:28)
	at com.spotify.folsom.reconnect.ReconnectingClient.lambda$new$1(ReconnectingClient.java:105)
	at com.spotify.folsom.reconnect.ReconnectingClient$$Lambda$28/0000000000000000.connect(Unknown Source)
	at com.spotify.folsom.reconnect.ReconnectingClient.retry(ReconnectingClient.java:157)
	at com.spotify.folsom.reconnect.ReconnectingClient.<init>(ReconnectingClient.java:120)
	at com.spotify.folsom.reconnect.ReconnectingClient.<init>(ReconnectingClient.java:102)
	at com.spotify.folsom.reconnect.ReconnectingClient.<init>(ReconnectingClient.java:76)
	at com.spotify.folsom.MemcacheClientBuilder.createReconnectingClient(MemcacheClientBuilder.java:651)
	at com.spotify.folsom.MemcacheClientBuilder.createClient(MemcacheClientBuilder.java:632)
	at com.spotify.folsom.MemcacheClientBuilder.createClients(MemcacheClientBuilder.java:608)
	at com.spotify.folsom.MemcacheClientBuilder.connectRaw(MemcacheClientBuilder.java:581)
	at com.spotify.folsom.MemcacheClientBuilder.connectAscii(MemcacheClientBuilder.java:558)
	at org.example.App.main(App.java:21)
	Suppressed: java.lang.UnsatisfiedLinkError: netty_transport_native_epoll_x86_64 (Not found in java.library.path)
		at java.base/java.lang.ClassLoader.loadLibraryWithPath(ClassLoader.java:1742)
		at java.base/java.lang.ClassLoader.loadLibraryWithClassLoader(ClassLoader.java:1694)
		at java.base/java.lang.System.loadLibrary(System.java:598)
		at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:566)
		at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:369)
		at java.base/java.security.AccessController.doPrivileged(AccessController.java:678)
		at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:361)
		at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:339)
		... 23 common frames omitted
12:51:56.947 [main] DEBUG io.netty.util.internal.NativeLibraryLoader - Unable to load the library 'netty_transport_native_epoll', trying other loading mechanism.
java.lang.UnsatisfiedLinkError: netty_transport_native_epoll (Not found in java.library.path)
	at java.base/java.lang.ClassLoader.loadLibraryWithPath(ClassLoader.java:1742)
	at java.base/java.lang.ClassLoader.loadLibraryWithClassLoader(ClassLoader.java:1694)
	at java.base/java.lang.System.loadLibrary(System.java:598)
	at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:369)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:678)
	at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:361)
	at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:339)
	at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
	at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:201)
	at io.netty.channel.epoll.Native.<clinit>(Native.java:61)
	at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:38)
	at com.spotify.folsom.client.DefaultRawMemcacheClient.lambda$static$0(DefaultRawMemcacheClient.java:96)
	at com.spotify.folsom.client.DefaultRawMemcacheClient$$Lambda$29/0000000000000000.get(Unknown Source)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:167)
	at com.spotify.folsom.client.DefaultRawMemcacheClient.connect(DefaultRawMemcacheClient.java:138)
	at com.spotify.folsom.reconnect.ReconnectingClient.lambda$new$0(ReconnectingClient.java:80)
	at com.spotify.folsom.reconnect.ReconnectingClient$$Lambda$27/0000000000000000.connect(Unknown Source)
	at com.spotify.folsom.authenticate.AuthenticatingClient.authenticate(AuthenticatingClient.java:28)
	at com.spotify.folsom.reconnect.ReconnectingClient.lambda$new$1(ReconnectingClient.java:105)
	at com.spotify.folsom.reconnect.ReconnectingClient$$Lambda$28/0000000000000000.connect(Unknown Source)
	at com.spotify.folsom.reconnect.ReconnectingClient.retry(ReconnectingClient.java:157)
	at com.spotify.folsom.reconnect.ReconnectingClient.<init>(ReconnectingClient.java:120)
	at com.spotify.folsom.reconnect.ReconnectingClient.<init>(ReconnectingClient.java:102)
	at com.spotify.folsom.reconnect.ReconnectingClient.<init>(ReconnectingClient.java:76)
	at com.spotify.folsom.MemcacheClientBuilder.createReconnectingClient(MemcacheClientBuilder.java:651)
	at com.spotify.folsom.MemcacheClientBuilder.createClient(MemcacheClientBuilder.java:632)
	at com.spotify.folsom.MemcacheClientBuilder.createClients(MemcacheClientBuilder.java:608)
	at com.spotify.folsom.MemcacheClientBuilder.connectRaw(MemcacheClientBuilder.java:581)
	at com.spotify.folsom.MemcacheClientBuilder.connectAscii(MemcacheClientBuilder.java:558)
	at org.example.App.main(App.java:21)
12:51:56.958 [main] DEBUG io.netty.util.internal.NativeLibraryLoader - netty_transport_native_epoll cannot be loaded from java.libary.path, now trying export to -Dio.netty.native.workdir: /tmp
java.lang.UnsatisfiedLinkError: netty_transport_native_epoll (Not found in java.library.path)
	at java.base/java.lang.ClassLoader.loadLibraryWithPath(ClassLoader.java:1742)
	at java.base/java.lang.ClassLoader.loadLibraryWithClassLoader(ClassLoader.java:1694)
	at java.base/java.lang.System.loadLibrary(System.java:598)
	at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
	at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:349)
	at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
	at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:201)
	at io.netty.channel.epoll.Native.<clinit>(Native.java:61)
	at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:38)
	at com.spotify.folsom.client.DefaultRawMemcacheClient.lambda$static$0(DefaultRawMemcacheClient.java:96)
	at com.spotify.folsom.client.DefaultRawMemcacheClient$$Lambda$29/0000000000000000.get(Unknown Source)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:167)
	at com.spotify.folsom.client.DefaultRawMemcacheClient.connect(DefaultRawMemcacheClient.java:138)
	at com.spotify.folsom.reconnect.ReconnectingClient.lambda$new$0(ReconnectingClient.java:80)
	at com.spotify.folsom.reconnect.ReconnectingClient$$Lambda$27/0000000000000000.connect(Unknown Source)
	at com.spotify.folsom.authenticate.AuthenticatingClient.authenticate(AuthenticatingClient.java:28)
	at com.spotify.folsom.reconnect.ReconnectingClient.lambda$new$1(ReconnectingClient.java:105)
	at com.spotify.folsom.reconnect.ReconnectingClient$$Lambda$28/0000000000000000.connect(Unknown Source)
	at com.spotify.folsom.reconnect.ReconnectingClient.retry(ReconnectingClient.java:157)
	at com.spotify.folsom.reconnect.ReconnectingClient.<init>(ReconnectingClient.java:120)
	at com.spotify.folsom.reconnect.ReconnectingClient.<init>(ReconnectingClient.java:102)
	at com.spotify.folsom.reconnect.ReconnectingClient.<init>(ReconnectingClient.java:76)
	at com.spotify.folsom.MemcacheClientBuilder.createReconnectingClient(MemcacheClientBuilder.java:651)
	at com.spotify.folsom.MemcacheClientBuilder.createClient(MemcacheClientBuilder.java:632)
	at com.spotify.folsom.MemcacheClientBuilder.createClients(MemcacheClientBuilder.java:608)
	at com.spotify.folsom.MemcacheClientBuilder.connectRaw(MemcacheClientBuilder.java:581)
	at com.spotify.folsom.MemcacheClientBuilder.connectAscii(MemcacheClientBuilder.java:558)
	at org.example.App.main(App.java:21)
	Suppressed: java.lang.UnsatisfiedLinkError: netty_transport_native_epoll (Not found in java.library.path)
		at java.base/java.lang.ClassLoader.loadLibraryWithPath(ClassLoader.java:1742)
		at java.base/java.lang.ClassLoader.loadLibraryWithClassLoader(ClassLoader.java:1694)
		at java.base/java.lang.System.loadLibrary(System.java:598)
		at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:566)
		at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:369)
		at java.base/java.security.AccessController.doPrivileged(AccessController.java:678)
		at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:361)
		at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:339)
		... 23 common frames omitted
12:51:57.175 [main] DEBUG io.netty.channel.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 4
12:51:57.486 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.noKeySetOptimization: false
12:51:57.486 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.selectorAutoRebuildThreshold: 512
12:51:57.557 [main] DEBUG io.netty.util.internal.PlatformDependent - org.jctools-core.MpscChunkedArrayQueue: available
12:51:58.167 [main] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.processId: 9804 (auto-detected)
12:51:58.176 [main] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv4Stack: false
12:51:58.176 [main] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv6Addresses: false
12:51:58.257 [main] DEBUG io.netty.util.NetUtil - Loopback interface: lo (lo, 0:0:0:0:0:0:0:1%lo)
12:51:58.260 [main] DEBUG io.netty.util.NetUtil - /proc/sys/net/core/somaxconn: 4096
12:51:58.285 [main] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.machineId: 00:1d:4f:ff:fe:fa:4d:d8 (auto-detected)
12:51:58.599 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.level: simple
12:51:58.600 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.targetRecords: 4
12:51:59.379 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numHeapArenas: 4
12:51:59.379 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numDirectArenas: 4
12:51:59.380 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.pageSize: 8192
12:51:59.380 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxOrder: 11
12:51:59.380 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.chunkSize: 16777216
12:51:59.380 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.tinyCacheSize: 512
12:51:59.381 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.smallCacheSize: 256
12:51:59.381 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.normalCacheSize: 64
12:51:59.381 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedBufferCapacity: 32768
12:51:59.382 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimInterval: 8192
12:51:59.382 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.useCacheForAllThreads: true
12:51:59.382 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedByteBuffersPerChunk: 1023
12:51:59.462 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.allocator.type: pooled
12:51:59.462 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.threadLocalDirectBufferSize: 0
12:51:59.463 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.maxThreadLocalCharBufferSize: 16384
12:52:00.961 [defaultRawMemcacheClient-1-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxCapacityPerThread: 4096
12:52:00.964 [defaultRawMemcacheClient-1-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxSharedCapacityFactor: 2
12:52:00.964 [defaultRawMemcacheClient-1-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.linkCapacity: 16
12:52:00.965 [defaultRawMemcacheClient-1-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.ratio: 8
12:52:00.987 [defaultRawMemcacheClient-1-1] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.checkAccessible: true
12:52:00.988 [defaultRawMemcacheClient-1-1] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.checkBounds: true
12:52:00.991 [defaultRawMemcacheClient-1-1] DEBUG io.netty.util.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@b8703ac
12:52:01.328 [ForkJoinPool-1-worker-3] INFO com.spotify.folsom.reconnect.ReconnectingClient - Successfully connected to 127.0.0.1:11211
value
12:52:02.089 [main] INFO com.spotify.folsom.reconnect.ReconnectingClient - Lost connection to 127.0.0.1:11211

Process finished with exit code 0

**Comment by spkrka** [comment]
It looks like this is debug logging from netty. If you want to get rid of these messages you can change the log level to INFO instead of DEBUG

**Comment by Robson96** [comment]
how do you do this?
