### ISSUE TITLE
IntegrationTest#testPartitionMultiget is flaky

### ISSUE THREAD

**Issue by danielnorberg** [spotify/folsom#47]
Seems like jmemcached might be flaky. Most test runs complete successfully but when it fails, the root cause seems to be an `IndexOutOfBoundsException` in jmemcached.

```
14:37:24.635 [New I/O server worker #1-1] ERROR c.t.j.p.t.MemcachedResponseEncoder - error
java.lang.IndexOutOfBoundsException: null
    at org.jboss.netty.buffer.SlicedChannelBuffer.checkIndex(SlicedChannelBuffer.java:222) ~[netty-3.2.3.Final.jar:na]
    at org.jboss.netty.buffer.SlicedChannelBuffer.getByte(SlicedChannelBuffer.java:93) ~[netty-3.2.3.Final.jar:na]
    at com.thimbleware.jmemcached.protocol.text.MemcachedCommandDecoder.eol(MemcachedCommandDecoder.java:53) ~[jmemcached-core-1.0.0.jar:na]
    at com.thimbleware.jmemcached.protocol.text.MemcachedCommandDecoder.decode(MemcachedCommandDecoder.java:68) ~[jmemcached-core-1.0.0.jar:na]
    at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:282) ~[netty-3.2.3.Final.jar:na]
    at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:214) ~[netty-3.2.3.Final.jar:na]
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:274) ~[netty-3.2.3.Final.jar:na]
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:261) ~[netty-3.2.3.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:350) ~[netty-3.2.3.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:281) ~[netty-3.2.3.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:201) ~[netty-3.2.3.Final.jar:na]
    at org.jboss.netty.util.internal.IoWorkerRunnable.run(IoWorkerRunnable.java:46) [netty-3.2.3.Final.jar:na]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_40]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_40]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_40]
14:37:24.638 [New I/O server worker #1-1] ERROR c.t.j.p.t.MemcachedResponseEncoder - error
java.io.IOException: Broken pipe
    at sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[na:1.8.0_40]
    at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47) ~[na:1.8.0_40]
    at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93) ~[na:1.8.0_40]
    at sun.nio.ch.IOUtil.write(IOUtil.java:51) ~[na:1.8.0_40]
    at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471) ~[na:1.8.0_40]
    at org.jboss.netty.channel.socket.nio.SocketSendBufferPool$PooledSendBuffer.transferTo(SocketSendBufferPool.java:239) ~[netty-3.2.3.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.NioWorker.write0(NioWorker.java:470) ~[netty-3.2.3.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.NioWorker.writeFromUserCode(NioWorker.java:388) ~[netty-3.2.3.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.handleAcceptedSocket(NioServerSocketPipelineSink.java:137) ~[netty-3.2.3.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.eventSunk(NioServerSocketPipelineSink.java:76) ~[netty-3.2.3.Final.jar:na]
    at org.jboss.netty.channel.Channels.write(Channels.java:611) ~[netty-3.2.3.Final.jar:na]
    at org.jboss.netty.channel.Channels.write(Channels.java:578) ~[netty-3.2.3.Final.jar:na]
    at com.thimbleware.jmemcached.protocol.text.MemcachedResponseEncoder.messageReceived(MemcachedResponseEncoder.java:103) ~[jmemcached-core-1.0.0.jar:na]
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:302) ~[netty-3.2.3.Final.jar:na]
    at com.thimbleware.jmemcached.protocol.MemcachedCommandHandler.handleSet(MemcachedCommandHandler.java:290) ~[jmemcached-core-1.0.0.jar:na]
    at com.thimbleware.jmemcached.protocol.MemcachedCommandHandler.messageReceived(MemcachedCommandHandler.java:186) ~[jmemcached-core-1.0.0.jar:na]
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:302) ~[netty-3.2.3.Final.jar:na]
    at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:317) ~[netty-3.2.3.Final.jar:na]
    at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:299) ~[netty-3.2.3.Final.jar:na]
    at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:214) ~[netty-3.2.3.Final.jar:na]
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:274) ~[netty-3.2.3.Final.jar:na]
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:261) ~[netty-3.2.3.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:350) ~[netty-3.2.3.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:281) ~[netty-3.2.3.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:201) ~[netty-3.2.3.Final.jar:na]
    at org.jboss.netty.util.internal.IoWorkerRunnable.run(IoWorkerRunnable.java:46) [netty-3.2.3.Final.jar:na]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_40]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_40]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_40]
14:37:24.639 [New I/O server worker #1-1] ERROR c.t.j.p.t.MemcachedResponseEncoder - error
java.nio.channels.ClosedChannelException: null
    at org.jboss.netty.channel.socket.nio.NioWorker.cleanUpWriteBuffer(NioWorker.java:637) ~[netty-3.2.3.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.NioWorker.writeFromUserCode(NioWorker.java:370) ~[netty-3.2.3.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.handleAcceptedSocket(NioServerSocketPipelineSink.java:137) ~[netty-3.2.3.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.eventSunk(NioServerSocketPipelineSink.java:76) ~[netty-3.2.3.Final.jar:na]
    at org.jboss.netty.channel.Channels.write(Channels.java:611) ~[netty-3.2.3.Final.jar:na]
    at org.jboss.netty.channel.Channels.write(Channels.java:578) ~[netty-3.2.3.Final.jar:na]
    at com.thimbleware.jmemcached.protocol.text.MemcachedResponseEncoder.messageReceived(MemcachedResponseEncoder.java:103) ~[jmemcached-core-1.0.0.jar:na]
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:302) ~[netty-3.2.3.Final.jar:na]
    at com.thimbleware.jmemcached.protocol.MemcachedCommandHandler.handleSet(MemcachedCommandHandler.java:290) ~[jmemcached-core-1.0.0.jar:na]
    at com.thimbleware.jmemcached.protocol.MemcachedCommandHandler.messageReceived(MemcachedCommandHandler.java:186) ~[jmemcached-core-1.0.0.jar:na]
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:302) ~[netty-3.2.3.Final.jar:na]
    at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:317) ~[netty-3.2.3.Final.jar:na]
    at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:299) ~[netty-3.2.3.Final.jar:na]
    at org.jboss.netty.handler.codec.frame.FrameDecoder.cleanup(FrameDecoder.java:333) ~[netty-3.2.3.Final.jar:na]
    at org.jboss.netty.handler.codec.frame.FrameDecoder.channelDisconnected(FrameDecoder.java:226) ~[netty-3.2.3.Final.jar:na]
    at org.jboss.netty.channel.Channels.fireChannelDisconnected(Channels.java:360) ~[netty-3.2.3.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.NioWorker.close(NioWorker.java:587) ~[netty-3.2.3.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.NioWorker.write0(NioWorker.java:513) ~[netty-3.2.3.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.NioWorker.writeFromUserCode(NioWorker.java:388) ~[netty-3.2.3.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.handleAcceptedSocket(NioServerSocketPipelineSink.java:137) ~[netty-3.2.3.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.eventSunk(NioServerSocketPipelineSink.java:76) ~[netty-3.2.3.Final.jar:na]
    at org.jboss.netty.channel.Channels.write(Channels.java:611) ~[netty-3.2.3.Final.jar:na]
    at org.jboss.netty.channel.Channels.write(Channels.java:578) ~[netty-3.2.3.Final.jar:na]
    at com.thimbleware.jmemcached.protocol.text.MemcachedResponseEncoder.messageReceived(MemcachedResponseEncoder.java:103) ~[jmemcached-core-1.0.0.jar:na]
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:302) ~[netty-3.2.3.Final.jar:na]
    at com.thimbleware.jmemcached.protocol.MemcachedCommandHandler.handleSet(MemcachedCommandHandler.java:290) ~[jmemcached-core-1.0.0.jar:na]
    at com.thimbleware.jmemcached.protocol.MemcachedCommandHandler.messageReceived(MemcachedCommandHandler.java:186) ~[jmemcached-core-1.0.0.jar:na]
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:302) ~[netty-3.2.3.Final.jar:na]
    at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:317) ~[netty-3.2.3.Final.jar:na]
    at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:299) ~[netty-3.2.3.Final.jar:na]
    at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:214) ~[netty-3.2.3.Final.jar:na]
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:274) ~[netty-3.2.3.Final.jar:na]
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:261) ~[netty-3.2.3.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:350) ~[netty-3.2.3.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:281) ~[netty-3.2.3.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:201) ~[netty-3.2.3.Final.jar:na]
    at org.jboss.netty.util.internal.IoWorkerRunnable.run(IoWorkerRunnable.java:46) [netty-3.2.3.Final.jar:na]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_40]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_40]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_40]
```

**Comment by danielnorberg** [comment]
This seems to affect the ascii implementation only.

It could be argued that folsom should handle `ERROR` results better as well.

```
SEVERE: input future failed.
com.spotify.folsom.MemcacheClosedException: Unexpected line: ERROR
    at com.spotify.folsom.client.DefaultRawMemcacheClient$RequestWritePromise.fail(DefaultRawMemcacheClient.java:374)
    at com.spotify.folsom.client.DefaultRawMemcacheClient$RequestWritePromise.tryFailure(DefaultRawMemcacheClient.java:366)
    at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:754)
    at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:655)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1113)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:633)
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:691)
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:626)
    at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:112)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:633)
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:691)
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:626)
    at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
    at com.spotify.folsom.client.DefaultRawMemcacheClient$ConnectionHandler.write(DefaultRawMemcacheClient.java:273)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:633)
    at io.netty.channel.AbstractChannelHandlerContext.access$1900(AbstractChannelHandlerContext.java:32)
    at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:908)
    at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:893)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
    at java.lang.Thread.run(Thread.java:745)
```

`ERROR` should perhaps not be an unexpected line.

**Comment by danielnorberg** [comment]
We're not the only ones hitting this.

https://code.google.com/p/jmemcache-daemon/issues/detail?id=32

Unfortunately this project does not seem to be actively maintained, so it seems unlikely that we'll see this issue addressed.

**Comment by spkrka** [comment]
We can export jmemcache-daemon to github and fork it? Either by asking for permission to adopt it or by changing the namespace.

**Comment by danielnorberg** [comment]
Sure, but I'd like to avoid investing any more time and resources into jmemcached. This seems to be just one issue out of many. If forking it onto github would be something we do only to fix the folsom tests, then I'm happy with this hack.

But if there was some other engineer with a lot of time on his/her hands... ;)

**Comment by spkrka** [comment]
Can we consider this fixed now with the monkey patch in place?
I also exported jmemcached here: https://github.com/krka/jmemcache-daemon/ - maybe can clean up the monkey patch at least by changing the package names and making a release.
