### ISSUE TITLE
Binary client throws IllegalStateException on retries?

### ISSUE THREAD

**Issue by odsod** [spotify/folsom#60]
Example stack trace:

```
com.spotify.folsom.MemcacheClosedException: opaque may not be set more than one
 at com.spotify.folsom.client.DefaultRawMemcacheClient.send(DefaultRawMemcacheClient.java:194)
 at com.spotify.folsom.reconnect.ReconnectingClient.send(ReconnectingClient.java:94)
 at com.spotify.folsom.ketama.KetamaMemcacheClient.sendSplitRequest(KetamaMemcacheClient.java:98)
 at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156)
 at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145)
 at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:202)
 at com.google.common.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:902)
 at com.google.common.util.concurrent.Futures$1$1.run(Futures.java:635)
 at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145)
 at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:202)
 at com.google.common.util.concurrent.Futures$CombinedFuture.access$400(Futures.java:1608)
 at com.google.common.util.concurrent.Futures$CombinedFuture$2.run(Futures.java:1686)
 at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:457)
 at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
 at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
 at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
 at com.spotify.folsom.client.DefaultRawMemcacheClient.send(DefaultRawMemcacheClient.java:194)
 at com.spotify.folsom.reconnect.ReconnectingClient.send(ReconnectingClient.java:94)
 at com.spotify.folsom.ketama.KetamaMemcacheClient.sendSplitRequest(KetamaMemcacheClient.java:98)
 at com.spotify.folsom.ketama.KetamaMemcacheClient.send(KetamaMemcacheClient.java:69)
 at com.spotify.folsom.retry.RetryingClient$1.create(RetryingClient.java:51)
 at com.google.common.util.concurrent.Futures$FallbackFuture$1.onFailure(Futures.java:471)
 at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156)
 at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:202)
 at com.google.common.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:902)
 at com.google.common.util.concurrent.Futures$1$1.run(Futures.java:635)
 at com.spotify.folsom.client.Utils$1.execute(Utils.java:44)
 at com.google.common.util.concurrent.Futures$1.run(Futures.java:632)
 at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156)
 at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145)
 at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:202)
 at com.google.common.util.concurrent.Futures$CombinedFuture.setExceptionAndMaybeLog(Futures.java:1704)
 at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:457)
 at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156)
 at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:202)
 at com.spotify.folsom.client.CallbackSettableFuture.run(CallbackSettableFuture.java:35)
 at com.spotify.folsom.reconnect.ReconnectingClient.send(ReconnectingClient.java:94)
 at com.google.common.util.concurrent.Futures$FallbackFuture$1.onFailure(Futures.java:471)
 at com.google.common.util.concurrent.Futures$6.run(Futures.java:1310)
 at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:202)
 at com.google.common.util.concurrent.Futures$1$1.run(Futures.java:635)
 at com.google.common.util.concurrent.Futures$1.run(Futures.java:632)
 at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:457)
 at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156)
 at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145)
 at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:202)
 at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
 at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
 at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
```

**Comment by spkrka** [comment]
Should be fixed with #61 - please re-open if you get it again.
